# Generated by Django 4.2.14 on 2025-03-26 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("custom_code", "0005_humantidesclasssubmission"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HumanTidesClassSubmission",
        ),
    ]
